name: 'Build FreeCAD'

on:
  workflow_run:
    workflows: [trigger]
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    name: Build FreeCAD
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Burn Baby Burn
        #continue-on-error: true
        run: docker run -e EXPORT_PKG=1 -e EXPORT_SRC=1 -e SYNC_DATABASE=1 -v $PWD/freecad:/pkg bonnee/makepkg:latest

      - name: Retrieve version info
        id: version
        run: |
          pkgbase="$(awk '{ if ($1 ~ /pkgbase/) {print $3} }' freecad/.SRCINFO)"
          pkgver="$(awk '{ if ($1 ~ /pkgver/) {print $3} }' freecad/.SRCINFO)"
          pkgrel="$(awk '{ if ($1 ~ /pkgrel/) {print $3} }' freecad/.SRCINFO)"
          arch="$(awk '{ if ($1 ~ /arch/) {print $3} }' freecad/.SRCINFO)"
          echo "::set-output name=pkgbase::$pkgbase"
          echo "::set-output name=pkgver::$pkgver"
          echo "::set-output name=pkgrel::$pkgrel"
          echo "::set-output name=arch::$arch"
          echo "::set-output name=filename::$(basename $(ls freecad/*.pkg.tar* | tail -n1))"

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.pkgver }}
          tag_name: ${{ steps.version.outputs.pkgver }}
          body: |
            # FreeCAD LinkStage3
            version ${{ steps.version.outputs.pkgver }}

      - name: Upload package to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./freecad/${{ steps.version.outputs.filename }}
          asset_name: ${{ steps.version.outputs.filename }}
          asset_content_type: application/x-tar

      - name: Generate PKGBUILD
        env:
          PKGVER: ${{ steps.version.outputs.pkgver }}
          FILENAME: ./freecad/${{ steps.version.outputs.filename }}
        run: utils/gen_pkgbuild.awk utils/PKGBUILD.template > PKGBUILD

      - name: Publish freecad-linkstage3-bin to the AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: freecad-linkstage3-bin
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Release ${{ steps.version.outputs.pkgver }}"

